x-kaniko: &kaniko
  image: gcr.io/kaniko-project/executor:debug-v0.16.0
  environment:
    DOCKER_CONFIG: /workspace/.docker
  volumes:
    - .:/workspace

version: "2"
services:
  docker:
    image: ${PACKAGE_NAME}:${GIT_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT}
        PACKAGE_NAME: ${PACKAGE_NAME}
        PACKAGE_VERSION: ${PACKAGE_VERSION}

  registry:
    image: registry:2.7.1
    volumes:
    - .cache:/var/lib/registry

  warmer:
    <<: *kaniko
    entrypoint: /kaniko/warmer
    command: |
      --cache-dir=/workspace/.cache
      --image=node:12.14.1-buster-slim

  kaniko:
    <<: *kaniko
    depends_on:
    - registry
    environment: 
      GIT_COMMIT: ${GIT_COMMIT}
      PACKAGE_NAME: ${PACKAGE_NAME}
      PACKAGE_VERSION: ${PACKAGE_VERSION}
    command: |
      --build-arg GIT_COMMIT=${GIT_COMMIT}
      --build-arg PACKAGE_NAME=${PACKAGE_NAME}
      --build-arg PACKAGE_VERSION=${PACKAGE_VERSION}
      --cache-dir=/workspace/.cache
      --cache-repo=registry:5000/cache
      --cache=true
      --context /workspace
      --dockerfile Dockerfile
      --insecure-registry=registry:5000
      --no-push
